### ISSUE TITLE
follow+unfollow not working anymore

### ISSUE THREAD

**Issue by SleepyMario** [thisSIDEofRANDOM/twash#1]
Hello, thanks for your nice little program. 
The problem is this: if i try to follow or unfollow these days using twash, it doesn't work anymore (it used to work). Do you have any idea what's the problem? The error is below, (when trying to follow a user called 'bentglasstube'):

----

Warning experimental function...
Following bentglasstube
{
 "error": "Unauthorized",
 "status": 401,
 "message": "Token invalid or missing required scope 'user_follows_edit'"
}

----

**Comment by thisSIDEofRANDOM** [comment]
Hey @SleepyMario glad you like it!

I think that means your current token wasn't applied using the new model rolled out by twitch awhile back.

You can either remove your token and let the app regenerate you a new one or if you just follow this link it should ask you to grant the new permissions:

```https://api.twitch.tv/kraken/oauth2/authorize?response_type=token&client_id=5k0hscvhd7l4o7iy1j3bo8tmpmvspq4&redirect_uri=https://thissideofrandom.github.io/twash/&scope=user_follows_edit%20user_read```

**Comment by SleepyMario** [comment]
Yup, that worked. Thanks for your help :)
