### ISSUE TITLE
Incorrect OAUTH or Twitch API down

### ISSUE THREAD

**Issue by SleepyMario** [thisSIDEofRANDOM/twash#2]
Hello, I haven't used this in a while, and now after I've reinstalled twash and try to use it I get this error: "Incorrect OAUTH or Twitch API down"

There surely has been an API change or 2, but I'm not knowledgeable enough to understand it all. Could you help?

**Comment by thisSIDEofRANDOM** [comment]
Looks like everything has moved to v5 or newapi. I'll start working on a conversion but had a quick look at the new helix endpoints and they aren't 1:1 with the old api.

Might need to rewrite some logic from the ground up as I don't see a single call for some things like list live streams from people I follow. Will see if I can knock this out this week.

**Comment by SleepyMario** [comment]
ok thanks!

**Comment by thisSIDEofRANDOM** [comment]
First commit done for the "new api" top games, top streams, followed channels, and pull top strems for a specific game should all be working.

Other experimental are broken due to no existing code flows for them.
